// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

type User struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	Email     string `json:"email"`
	CreatedAt string `json:"created_at"`
}
